# Examen A Módulo 1 - Optimización.

**Lea cuidadosamente las siguientes indicaciones antes de comenzar el examen:**
- Para resolver el examen edite este mismo archivo y renómbrelo de la siguiente manera: *Examen1_ApellidoNombre*, donde *ApellidoNombre* corresponde a su apellido paterno con la inicial en mayúscula, seguido de su primer nombre con la inicial en mayúscula **sin tildes**. Por ejemplo, en mi caso el nombre del archivo sería *Examen1_MoralesGabriel*.
- Resuelva los puntos en el espacio provisto. Si requiere agregar más celdas para código o escritura, hágalo (`Esc`,`B`) o (`Esc`,`A`).
- Recuerde que también se está evaluando su capacidad de interpretar los resultados. Escriba sus interpretaciones/conclusiones en celdas utilizando *Markdown*.
- El formato de presentación de todo el examen en general debe ser adecuado. Use tamaños de letra, colores, etiquetas, etcétera.
- No se resuelven dudas de ningún tipo por los profesores de la asignatura. Por favor, absténgase de preguntar.
- Revise bien el tipo de examen. Sólo se le calificará si realiza el tipo de examen asignado.

## 1. Optimización de funciones con `Sympy`

Funciones permitidas: subs, solve, var, expresiones matemáticas


Un cine cobra 86 pesos la entrada estándar y 60 pesos la entrada a estudiantes. Una sala con capacidad para 120 personas se ocupó al 70\%. Los ingresos para esa función fueron de 6,600 MXN. ¿Cuántos estudiantes entraron?

*  $$ 6600 = 86x + 60y $$
*  $$ 84 = x + y $$











In [124]:
Cap= 120 * 0.7
Cap

84.0

In [126]:
import sympy as sp
sp.var("x")
sp.var("y")
Din = 86*x+60*y-6600
Pub = x + y - Cap
x_y=sp.solve(Pub,x)[0]
Ry=sp.solve(Din.subs(x,x_y),y)
Ry

[24.0000000000000]

24 estudiantes

El cine ofrece combos y opciones individuales. El combo 'amigos' tiene un costo de 156 MXN y consiste de 2 refrescos y unas palomitas. Existe también el combo 'nachos' que tiene un costo de 112 MXN y consiste de un refresco y una orden de nachos. Por separado el refresco tiene un costo de 60 MXN, las palomitas 58 MXN y los nachos 72 MXN. Se obtuvo un total de 6450 de ingresos en dulcería:

- 38 combos vendidos
- 70 refrescos vendidos
- 33 órdenes de palomitas grandes vendidas
- 16 órdenes de nachos vendidas

¿Cuántas personas compraron palomitas sueltas?

*  $ Cn + Ca = 38$

*  $ r + Cn + Ca = 70$

* $ p + Ca = 33$

*  $ n + Cn = 16$

*  $ 60r + 72n + 58p + 156Ca + 112Cn = 6450$

In [131]:
import sympy as sp

sp.var("r")
sp.var("p")
sp.var("Ca")
sp.var("n")
sp.var("Cn")


f_costo = 60*r + 58*p + 72*n + 156*Ca + 112*Cn - 6450

combos = Cn + Ca -38
refrescos  = r + Cn + 2*Ca - 70 
palomitas = p + Ca - 33
nachos = n + Cn - 16

Cn_Ca = sp.solve(combos,Cn)[0] # Despejo Cn en terminos de Ca

# Se sustituye Ca en la ecuacion de los refrescos
sus_Ca_r = refrescos.subs(Cn, Cn_Ca) 
# Se sustituye Ca en la ecuacion de los nachos
sus_Ca_n = nachos.subs(Cn, Cn_Ca) 

# Despejamos r de la nueva ecuacion de refrescos
r_desp = sp.solve(sus_Ca_r, r)[0] #r en términos de Ca
# Despejamos n de la nueva ecuacion de nachos
n_desp = sp.solve(sus_Ca_n, n)[0] # n en términos de Ca

p_desp = sp.solve(palomitas, p)[0] # Despejamos p de la  ecuacion de palomitas

total_Ca = f_costo.subs(r, r_desp).subs(n, n_desp).subs(p, p_desp).subs(Cn, Cn_Ca) # Sustituyo r, n, p y Cn en f_costo para tener Ca
Ca_def = sp.solve(total_Ca, Ca)[0] # Obtengo Ca

p_def = p_desp.subs(Ca, Ca_def) # Sustituir Ca para tener las palomitas sueltas
p_def

5

Palomitas sueltas: 5

## 2. Programación lineal

Una empresa produce costales de 3 tipos de fertilizantes para diferentes aplicaciones utilizando cuantro componentes químicos: azufre, potasio, fósforo y nitrógeno. La información de cada tonelada de fertilizante es:


<table>
  <tr>
      <th>Fertilizante</th>
      <th>Fósforo</th>
      <th>Azufre</th>
      <th>Potasio</th>
      <th>Nitrógeno</th>
      <th>Precio de venta </th>
  </tr>
  <tr>
      <td>A</td>
      <td>3 kg</td>
      <td>5 kg</td>
      <td>4 kg</td>
      <td>2 kg </td>
      <td>\$40000</td>
  </tr>
  <tr>
      <td>B</td>
      <td>4 kg</td>
      <td>3 kg</td>
      <td>2 kg</td>
      <td>1 kg</td>
      <td>\$50000</td>
  </tr>
  <tr>
      <td>C</td>
      <td>5 kg</td>
      <td>2 kg</td>
      <td>3 kg</td>
      <td>4 kg</td>
      <td>\$60000</td>
  </tr>

</table>

La máquina que se usa para mezclar el fertilizante C necesita mantenimiento y por lo tanto sólo puede mezclar 10 toneladas. Además, hay un pedido de 8 toneladas del fertilizante A.

Dado que en almacén se tienen 90 kg de fósforo, 120 kg de nitrógeno, 80 kg de azufre y 95 kg de potasio, ¿cuánto recomiendas que se mezcle de cada fertilizante? (Nota: No se permiten fracciones de toneladas)

* maximizar ganancia
* Xa, Xb, Xc
* f(Xa, Xb, Xc)=40000Xa+50000Xb+60000Xc
* $$ P \leq90\  $$
* $$ N \leq120\  $$
* $$ S \leq80\  $$
* $$ K \geq95\  $$
 $$ $$
*  $$ 3Xa+ 4Xb + 5Xc \leq90\ $$
*  $$ 2Xa+ 1Xb + 4Xc \leq120\ $$
*  $$ 5Xa+ 3Xb + 2Xc \leq80\ $$
*  $$ 4Xa+ 2Xb + 3Xc \leq95\ $$
*  $$ A  \geq8\ $$
*  $$ C  \leq10\ $$

In [140]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.optimize as opt
import sympy as sp

c = np.array([-40000, -50000, -60000])

Aub = np.array([
               [3, 4, 5],
               [2, 1, 4],
               [5, 3, 2],
               [4, 2, 3],
               [ -1,  0,  0,],
               [ 0,  0,  -1]
])

bub = np.array([90, 120, 80, 95, -8, -10])

opt.linprog(c, Aub, bub, integrality=1)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -1120000.0
              x: [ 8.000e+00  4.000e+00  1.000e+01]
            nit: -1
          lower:  residual: [ 8.000e+00  4.000e+00  1.000e+01]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  6.000e+01  8.000e+00  2.500e+01
                              0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: -1120000.0
        mip_gap: 0.0

In [142]:
sol = opt.linprog(c, Aub, bub, integrality=1)
sol.x

array([ 8.,  4., 10.])

Lo recomendado a mezclar sería:

+ 8 toneladas del fertilizante A
+ 4 toneladas del fetilizante B
+ 10 toneladas del fertilizante C

¿Cuál es el ingreso total?

El ingresos total es: $ 1120000  #sol.fun*-1 (para quitarle el -1)

¿Cuánto fósforo quedó en almacén?

0 # Asi lo indican los residuos de la restriccion

## 3. Regresión lineal

Se quiere predecir la resistencia a la compresión de concreto en función de las proporciones de los componentes en la mezcla (cemento, arena, agua, agregado). La constructora que está realizando el análisis tiene datos históricos donde se registraron cantidades de materia y la resistencia medida:

In [155]:
import pandas as pd
data = {
    'Cemento (kg)': [350, 400, 300, 450, 380, 410, 320, 370, 390, 360,
                     340, 430, 315, 405, 425, 345, 395, 355, 440, 310,
                     385, 370, 425, 335],
    'Arena (kg)': [600, 550, 700, 500, 580, 540, 650, 590, 570, 610,
                   630, 520, 660, 545, 530, 620, 560, 605, 515, 670,
                   575, 590, 535, 625],
    'Agua (kg)': [180, 160, 200, 170, 175, 165, 185, 172, 170, 190,
                  182, 165, 195, 175, 168, 180, 175, 185, 162, 198,
                  178, 172, 170, 180],
    'Agregado (kg)': [1000, 1100, 950, 1200, 1050, 1150, 980, 1020, 1080, 970,
                      990, 1120, 950, 1060, 1140, 990, 1040, 1010, 1160, 940,
                      1070, 1030, 1110, 1025],
    'Resistencia a la compresión (MPa)': [35, 42, 30, 50, 38, 44, 32, 36, 40, 34,
                                          33, 48, 31, 43, 47, 37, 41, 35, 49, 29,
                                          39, 36, 45, 33]
}
data = pd.DataFrame(data)
data

Cemento (kg)  Arena (kg)  Agua (kg)  Agregado (kg)  \
0            350         600        180           1000   
1            400         550        160           1100   
2            300         700        200            950   
3            450         500        170           1200   
4            380         580        175           1050   
5            410         540        165           1150   
6            320         650        185            980   
7            370         590        172           1020   
8            390         570        170           1080   
9            360         610        190            970   
10           340         630        182            990   
11           430         520        165           1120   
12           315         660        195            950   
13           405         545        175           1060   
14           425         530        168           1140   
15           345         620        180            990   
16           395         560        175           1040   
17           355         605        185           1010   
18           440         515        162           1160   
19           310         670        198            940   
20           385         575        178           1070   
21           370         590        172           1030   
22           425         535        170           1110   
23           335         625        180           1025   

    Resistencia a la compresión (MPa)  
0                                  35  
1                                  42  
2                                  30  
3                                  50  
4                                  38  
5                                  44  
6                                  32  
7                                  36  
8                                  40  
9                                  34  
10                                 33  
11                                 48  
12                                 31  
13                                 43  
14                                 47  
15                                 37  
16                                 41  
17                                 35  
18                                 49  
19                                 29  
20                                 39  
21                                 36  
22                                 45  
23                                 33

Ajusta un modelo utilizando mínimos cuadrados para encontrar una función que pueda predecir la resistencia del concreto.

In [158]:
import numpy as np
import scipy.optimize as opt

y=data['Resistencia a la compresión (MPa)']
x_1=data['Cemento (kg)']
x_2=data['Arena (kg)']
x_3=data['Agua (kg)']
x_4=data['Agregado (kg)']

n=len(y)
ones=np.ones([n,1])
xf1=np.reshape(x_1,(n,1))
xf2=np.reshape(x_2,(n,1))
xf3=np.reshape(x_3,(n,1))
xf4=np.reshape(x_4,(n,1))
X=np.hstack((ones, xf1, xf2, xf3, xf4))


y_v=np.reshape(y,(n,1))


n,p=X.shape
b=np.random.random(p)

def f(b,X, y):
  b=np.reshape(b, [p, 1])
  y_pr=X@b
  error=y_pr-y
  rss=error.T@error
  return rss
rss=opt.minimize(f, b, args=(X, y_v))
rss

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 29.849891689352127
        x: [-5.576e+01  1.374e-01  2.436e-02  1.949e-02  2.397e-02]
      nit: 12
      jac: [ 0.000e+00  1.669e-06  1.907e-06  7.153e-07  4.053e-06]
 hess_inv: [[ 4.531e+02 -5.308e-01 ...  1.438e-01 -5.089e-03]
            [-5.308e-01  8.546e-04 ... -4.346e-04 -9.193e-05]
            ...
            [ 1.438e-01 -4.346e-04 ...  1.182e-03  8.012e-05]
            [-5.089e-03 -9.193e-05 ...  8.012e-05  4.315e-05]]
     nfev: 144
     njev: 24

¿Qué efecto tiene cada factor en la resistencia de la mezcla?

Cada elemento aporta sus propiedades para que juntos, se alcance la resistencia deseada

¿Cuál será la resistencia si mezclo 390 kg de cemento, 570 kg de arena, 170 kg de agua y 1080 kg de agregado?

In [167]:
Cemento = (rss.x[1]*390)
Arena= (rss.x[2]*570)
Agua = (rss.x[3]*170)
Agregado = (rss.x[4]*1080)
Resistencia = Cemento + Arena + Agua + Agregado + rss.x[0]
Resistencia 

40.90572531015449

La resistencia será de 40.905724812374956

## 4. Regresión logística

Un equipo de ingenieros quiere saber si una muestra de concreto hidráulico fallará o no bajo determinadas condiciones, basándose en experiencias pasadas.

<table>
  <thead>
    <tr>
      <th>Resistencia a la compresión (MPa)</th>
      <th>Edad del concreto (días)</th>
      <th>Relación agua-cemento</th>
      <th>Falla (Sí/No)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>25</td>
      <td>28</td>
      <td>0.45</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>40</td>
      <td>56</td>
      <td>0.35</td>
      <td>No</td>
    </tr>
    <tr>
      <td>30</td>
      <td>28</td>
      <td>0.50</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>50</td>
      <td>90</td>
      <td>0.30</td>
      <td>No</td>
    </tr>
    <tr>
      <td>35</td>
      <td>28</td>
      <td>0.40</td>
      <td>Sí</td>
    </tr>
    <tr>
      <td>55</td>
      <td>120</td>
      <td>0.32</td>
      <td>No</td>
    </tr>
    <tr>
      <td>45</td>
      <td>60</td>
      <td>0.36</td>
      <td>No</td>
    </tr>
    <tr>
      <td>20</td>
      <td>7</td>
      <td>0.55</td>
      <td>Sí</td>
    </tr>
  </tbody>
</table>


1. ¿Qué factor afecta más? (Utiliza un vector de ceros como tu beta inicial)

In [174]:
Resistencia =[25, 40, 30, 50, 35, 55, 45, 20]
Edad =[28, 56, 28, 90, 28, 120, 60, 7]
Relacion =[0.45, 0.35, 0.50, 0.30, 0.40, 0.32, 0.36, 0.55]
Falla =[1, 0, 1, 0, 1, 0, 0, 1] # 1 = Si 0 = No

n=len(Falla)
ones=np.ones([n, 1])
B_Resistencia=np.reshape(Resistencia, (n, 1))
B_Edad=np.reshape(Edad, (n, 1))
B_Relacion=np.reshape(Relacion, (n, 1))

X=np.hstack((ones, B_Resistencia, B_Edad, B_Relacion))

y_v=np.reshape(Falla,(n, 1))

def prediccion(b, X):
  return 1/(1+np.exp(-X@b))

def J(b, X, y):
  epsilon=1e-100
  n, p=X.shape
  b=np.reshape(b, [p, 1])
  y_prediccion=prediccion(b, X)
  e=y*np.log(y_prediccion+epsilon)+(1-y)*np.log(1-y_prediccion+epsilon)
  return-np.sum(e)

b=[0, 0, 0, 0]

rrs=opt.minimize(J, b, args=(X, y_v))
rrs

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 2.1236079788292108e-07
        x: [ 2.223e+01  2.043e+00 -2.254e+00  1.432e+01]
      nit: 28
      jac: [ 9.686e-08  5.215e-06  7.354e-06  4.470e-08]
 hess_inv: [[ 3.268e+06  2.756e+05 -3.119e+05  2.104e+06]
            [ 2.756e+05  2.324e+04 -2.630e+04  1.775e+05]
            [-3.119e+05 -2.630e+04  2.977e+04 -2.009e+05]
            [ 2.104e+06  1.775e+05 -2.009e+05  1.355e+06]]
     nfev: 155
     njev: 31

El factor que más afecta es la relación agua-cemento

2. Calcula la probabilidad de falla para una muestra con las siguientes características:
- Resistencia a la compresión: 38 MPa
- Edad del concreto: 30 días
- Relación agua-cemento: 0.40

In [179]:
Resistencia_a_la_compresión = (rss.x[1]*38)
Edad_del_concreto = (rss.x[2]*30)
Relación_agua_cemento = (rss.x[3]*.4)
(Resistencia_a_la_compresión + Edad_del_concreto + Relación_agua_cemento +rss.x[0])*-1

49.799640840346676

La probabilidad de falla es de 49.79971185789123. 49% o bien 49.8%