# T04 - Programación lineal


## Santiago Padillla Arias EXP:750985 Fecha: 11/09/2024


### 02 Programación lineal.ipynb

In [42]:
# PROFE PERDONE MIS FALTAS DE ORTOGRAFIA ESTOY CON EL TECLADO EN INGLES Y NO ME DEJA PONER ACENTOS

#### Ejercicio 1
1. Una multinacional farmacéutica desea fabricar un compuesto nutritivo a base de dos productos A y B.  El producto A contiene  $30\%$ de proteínas,  un $1\%$ de grasas y un  $10\%$ de azúcares.  El producto B  contiene  un  $5\%$  de proteínas,  un  $7\%$ de grasas  y un  $10\%$  de  azúcares.
El compuesto debe de tener,  al menos, $25g$ de proteínas,  $6g$ de grasas y $30g$ de azúcares.  El coste del producto A es de $0.6$ u.m./g  y el de B es de $0.2$  u.m./g

Se desea encontrar la cantidad en gramos de cada producto para que el coste total sea mínimo.

Formular el problema de decidir cuánto hacer de cada producto como un problema de programación lineal.

1. Identificar criterio de optimizacion minimizar $\$$ costo de producto como nuevo
2. Variables de control:
  - gramos de A --> $x_A$
  - gramos de B --> $x_B$
3. FUncion de costo
 - $ f(x_A, x_B) = 0.6 \frac{\$}{g}x_A + 0.2 \frac{$}{g}x_B $
4. Informacion adicional
- Producto A contiene
    - 30 % de proteina
    - 1 % de grasas
    - 10 % de azucares


- Producto B contiene
    - 5 % de proteina
    - 7 % de grasas
    - 10 % de azucares

Producto final debe contener
    - Al menos 25 g de proteina
    - Al menos 6 g de grasas
    - Al menos 30 g de azucares

$$ \min{x_A, x_B} 0.6 x_A + 0.2 x_B$$
$$ \text{s.t.}$$

$$ 0.30 x_A + 0.05  x_B \geq 25\  $$ 

$$ 0.01 x_A + 0.07  x_B \geq 6\  $$ 

$$ 0.10 x_A + 0.10  x_B \geq 30\  $$ 

In [34]:
import numpy as np

c = np.array([0.6,0.2])

Aub = np.array ([
    [-0.30, -0.05],
    [-0.01, -0.07],
    [-0.10, -0.10]
])

bub = np.array([-25, -6, -30])

import scipy.optimize as opt

sol = opt.linprog(c, Aub, bub)
sol

# Aub @ sol.x  # Arroba multiplica vectores y matrices, el punto x, de la solucion encontrada solo usa la parte de x

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 76.0
              x: [ 4.000e+01  2.600e+02]
            nit: 2
          lower:  residual: [ 4.000e+01  2.600e+02]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.260e+01  0.000e+00]
                 marginals: [-1.600e+00 -0.000e+00 -1.200e+00]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

Las medidas de los productos debe ser de:  
 - **40** para el producto A.
 - **260** para el producto B.

Nota: Resultados se obtienen a partir de las posiciones de las matrices, se deben interpretar resultados.

#### Ejercicio 2
Una  fábrica  de  carrocerías  de  automóviles  y camiones  tiene  dos naves. 

+ En  la nave A,  para  hacer  la  carrocería  de  un  camión,  se  invierten  siete  días-operario,  para  fabricar  la  de  un  coche  se  precisan dos días-operario.

+ En la nave B se invierten tres días operario tanto en carrocerías de camión como de coche. 

Por limitaciones de mano de obra y maquinaria, la nave A dispone de $300$ días operario, y la nave B de $270$ días-operario.

Si los beneficios que se obtienen por cada camión son de $600$ u.m y por  cada  automóvil  $200$ u.m,  ¿cuántas  unidades  de  cada  uno  se deben  producir  para maximizar las  ganancias? 

**Nota:** el problema $\max_{\boldsymbol{x}}\boldsymbol{g}(\boldsymbol{x})$ es equivalente a $\min_{\boldsymbol{x}}-\boldsymbol{g}(\boldsymbol{x})$.

1. Identificar criterio de optimizacion maximizar $\$$ beneficios
   
2. Variables de control:
  - Automoviles --> $A$
  - Camiones --> $C$

3. FUncion de costo
 - $ 200 A + 600 B = Costo $

4. Informacion adicional:

Operarios
    - Nave A: 300
    - Nave B: 270
    
- Tardanza en nave A:
    - 2 dias para automovil
    - 7 dias para camion

- Tardanza nave B:
    - 3 dias para automovil y 3 para camion



In [68]:
import numpy as np

c = np.array([-200, -600])

Aub = np.array ([
    [2, 7],
    [3, 3]
])

bub = np.array([300, 270])

import scipy.optimize as opt

sol = opt.linprog(c, Aub, bub, integrality=1)
sol

# Aub @ sol.x  # Arroba multiplica vectores y matrices, el punto x, de la solucion encontrada solo usa la parte de x

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -27600.0
              x: [ 6.600e+01  2.400e+01]
            nit: -1
          lower:  residual: [ 6.600e+01  2.400e+01]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: -27600.0
        mip_gap: 0.0

- El beneficio debe ser de:  **27600.0**
- Con la produccion de:
    - 66 automoviles
    - 24 camion
 
Nota: Resultados se obtienen a partir de las posiciones de las matrices, se deben interpretar resultados.

#### Ejercicio 3
Mónica hace aretes y cadenitas de joyería. Es tan buena, que todo lo que hace lo vende.

Le toma 30 minutos hacer un par de aretes y una hora hacer una cadenita, y como Mónica también es estudihambre, solo dispone de 10 horas a la semana para hacer las joyas. Por otra parte, el material que compra solo le alcanza para hacer 15 unidades (el par de aretes cuenta como unidad) de joyas por semana.

La utilidad que le deja la venta de las joyas es $\$15$ en cada par de aretes y $\$20$ en cada cadenita.

¿Cuántos pares de aretes y cuántas cadenitas debería hacer Mónica para maximizar su utilidad?


1. Identificar criterio de optimizacion maximizar $\$$ beneficios
   
2. Variables de control:
  - Aretes --> $A$
  - Cadenas --> $C$

3. FUncion de costo
 - $ 15 A + 20 C = Costo $

4. Informacion adicional:

Tiempo: $ .50 A +  1 C \leq 10\  $

Material usado: $ A + C \leq 15\  $ 


In [6]:
import numpy as np

c = np.array([-15, -20])

Aub = np.array ([
    [.5, 1],
    [1, 1]
])

bub = np.array([10, 15])

import scipy.optimize as opt

sol = opt.linprog(c, Aub, bub, integrality=1)
sol

# Aub @ sol.x  # Arroba multiplica vectores y matrices, el punto x, de la solucion encontrada solo usa la parte de x

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -250.0
              x: [ 1.000e+01  5.000e+00]
            nit: -1
          lower:  residual: [ 1.000e+01  5.000e+00]
                 marginals: [ 0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf]
                 marginals: [ 0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: -250.0
        mip_gap: 0.0

- La ganancia (beneficio) debe ser de:  **250.0**
- Con la produccion de:
    - 10 pares de aretes
    - 5 collares
 
     
Nota: Resultados se obtienen a partir de las posiciones de las matrices, se deben interpretar resultados.

#### Ejercicio 4
Problema de transporte 1
- **Referencia**: http://bdigital.unal.edu.co/5037/4/guillermojimenezlozano.2006_Parte1.pdf

Una  empresa tiene dos fábricas A y B.  En ellas  se fabrica un determinado  producto, a razón de 500  y 400 unidades por día respectivamente.  El producto  ha  de  ser distribuido posteriormente  a  tres  centros  C,  D  y  E,  que  requieren,  respectivamente,  200,  300  y  400  unidades.  Los  costos  de  transportar cada unidad del producto desde cada fábrica a cada centro distribuidor son los  indicados  en la tabla  siguiente: 

Factoría|C|D|E|Fabricación (Unidades)
:----|----|----|----|----
A|  50 u.m|60 u.m|10 u.m|500 u
B|  25 u.m|40 u.m|20 u.m|400 u
Demanda|200|300|400|

**¿De qué manera  deben  organizar  el transporte a fin de que los gastos sean mínimos?**


Resolver con `linprog`

1. Identificar criterio de optimizacion minimizar $\$$ beneficios
   
2. Variables de control:
  - Factoria A centro C--> $AC$
  - Factoria B centro C--> $BC$
  - Factoria A centro D--> $AD$
  - Factoria B centro D--> $BD$
  - Factoria A centro E--> $AE$
  - Factoria B centro E--> $BE$

3. FUncion de costo
 - $ 50AC + 25BC + 60AD +40BD + 10AE + 20BE = Costo $

4. Informacion adicional:

Centro C: $ 50AC + 25BC \geq 200\  $

Centro D: $ 60AD +40BD \geq 300\  $

Centro E: $ 10AE + 20BE \geq 400\  $


In [20]:
# esta no se si estaba bien

import numpy as np

c = np.array([50, 25, 60, 40, 10, 20])

Aub = np.array ([
     [-50, -25,  0,  0,  0,  0], 
     [0,    0, -60, -40, 0, 0], 
     [0,    0,   0,  0, -10, -20]
])

bub = np.array([-200, -300, -400])

import scipy.optimize as opt

sol = opt.linprog(c, Aub, bub, integrality=1)
sol

# Aub @ sol.x  # Arroba multiplica vectores y matrices, el punto x, de la solucion encontrada solo usa la parte de x

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 900.0
              x: [ 0.000e+00  8.000e+00  5.000e+00  0.000e+00  4.000e+01
                   0.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  8.000e+00  5.000e+00  0.000e+00
                              4.000e+01  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 900.0
  

In [28]:
# esta segun yo si estaba bien

import numpy as np

c = np.array([50, 60, 10, 25, 40, 20])

Aub=np.array([
    [-50,0, 0, -25, 0, 0], 
    [0, -60, 0, 0, -40, 0], 
    [0, 0, -10, 0, 0, -20]
])

bub = np.array([-200, -300, -400])

import scipy.optimize as opt

sol = opt.linprog(c, Aub, bub, integrality=1)
sol


        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 900.0
              x: [ 0.000e+00  5.000e+00  4.000e+01  8.000e+00  0.000e+00
                   0.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  5.000e+00  4.000e+01  8.000e+00
                              0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
 mip_node_count: 1
 mip_dual_bound: 900.0
  

- La ganancia (beneficio) debe ser de:  **900.0**
- Con la produccion de:
    - 4AC
    - 5AD
    - 8AE
 
     
Nota: Resultados se obtienen a partir de las posiciones de las matrices, se deben interpretar resultados.

#### Ejercicio 5
El objetivo de este problema es determinar la mejor estrategia de inversión, dados diferentes tipos de bono, la máxima cantidad que puede ser invertida en cada bono, el porcentaje de retorno y los años de madurez. También hay una cantidad fija de dinero disponible ($\$750,000$). Por lo menos la mitad de este dinero debe ser invertido en bonos con 10 años o más para la madurez. Se puede invertir un máximo del $25\%$ de esta cantidad en cada bono. Finalmente, hay otra restricción que no permite usar más de $35\%$ en bonos de alto riesgo.

Existen seis (6) opciones de inversión con las letras correspondientes $A_i$

1. $A_1$:(Tasa de retorno=$8.65\%$; Años para la madurez=11, Riesgo=Bajo)
1. $A_2$:(Tasa de retorno=$9.50\%$; Años para la madurez=10, Riesgo=Alto)
1. $A_3$:(Tasa de retorno=$10.00\%$; Años para la madurez=6, Riesgo=Alto)
1. $A_4$:(Tasa de retorno=$8.75\%$; Años para la madurez=10, Riesgo=Bajo)
1. $A_5$:(Tasa de retorno=$9.25\%$; Años para la madurez=7, Riesgo=Alto)
1. $A_6$:(Tasa de retorno=$9.00\%$; Años para la madurez=13, Riesgo=Bajo)

Lo que se quiere entonces es maximizar el retorno que deja la inversión.

Este problema puede ser resuelto con programación lineal. Formalmente, puede ser descrito como:

$$\max_{A_1,A_2,...,A_6}\sum^{6}_{i=1} A_iR_i,$$

donde $A_i$ representa la cantidad invertida en la opción, y $R_i$ representa la tasa de retorno respectiva.

1. Identificar criterio de optimizacion maximizar $\$$ beneficios
   
2. Variables de control:
  - Opcion de inversion 1--> $A_1$
  - Opcion de inversion 2--> $A_2$
  - Opcion de inversion 3--> $A_3$
  - Opcion de inversion 4--> $A_4$
  - Opcion de inversion 5--> $A_5$
  - Opcion de inversion 6--> $A_6$

3. FUncion de costo
 - $  0.0865A_1 + 0.95A_2 +0.1A_3 +0.0875A_4 +0.0925A_5 +.09 A_6 = Costo $

4. Informacion adicional:

Presupuesto total: $ A_1 + A_2 +A_3 + A_4 + A_5 + A_6 \geq 75000\  $

Presupuesto a 10 años: $ 60AD +40BD \geq 300\  $

Bono: $ A_1 = A_2 = A_3 = A_4 = A_5 = A_6 \leq 187500\  $

Bono Riesgo Alto: $  A_2 + A_3 + A_5 \geq 262500\  $

In [49]:
import numpy as np
import scipy.optimize as opt
c=np.array ([-.0865,  -.095, -.1, -.0875, -.0925, -.09])
Aub=np.array([
    [1,  1,  1,  1,  1, 1],
    [-1, -1, 0, -1, 0, -1], 
    [1,  0,  0,  0, 0,  0], 
    [0,  1,  0,  0, 0,  0], 
    [0,  0,  1,  0, 0,  0], 
    [0,  0,  0,  1, 0,  0], 
    [0,  0,  0,  0, 1,  0], 
    [0,  0,  0,  0, 0,  1], 
    [0,  1,  1,  0, 1,  1]
])

bub=np.array ([750000,   -375000,  187500, 187500, 187500, 187500, 187500, 187500, 262500])

sol=opt.linprog(c, Aub, bub)
sol

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -58500.0
              x: [ 1.875e+05  7.500e+04  1.875e+05  1.875e+05  0.000e+00
                   0.000e+00]
            nit: 1
          lower:  residual: [ 1.875e+05  7.500e+04  1.875e+05  1.875e+05
                              0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              2.500e-03  5.000e-03]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 1.125e+05  7.500e+04  0.000e+00  1.125e+05
                              0.000e+00  0.000e+00  1.875e+05  1.875e+05
                      

- Retorno debe ser de:  **58500.0**
- Montos:
    - A_1 = A_3 = A_4 = 187500
    - A_2 = 7500
    - A_5 = A_6 = 0
     
Nota: Resultados se obtienen a partir de las posiciones de las matrices, se deben interpretar resultados.

## A05

## Ejercicio 1

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en 100 gramos, se deben tener por lo menos 9 gramos de proteína y  7 gramos de grasa. Así mismo, no se debe tener más de 2.5 gramos de fibra y 0.5 gramos de sal.


![](Ejercicio1_A05.png)

1. Identificar criterio de optimizacion minimizar $\$$ costo de producto como nuevo
2. Variables de control:
  - Pollo --> P
  - Carne --> C
  - Cordero --> Cor
  - Arroz --> A
  - Trigo --> T
  - Gel --> G
  - Proteina --> Pro
  - Grasa --> Gra
  - Fibra --> F
  - Sal --> S
    
3. Funcion de costo
 - $ P0.012 + 0.009 C + 0.010 Cor + 0.003 A +  0.005 T + 0.002 G = Costo$

4. Informacion adicional
   - $\text{En 100 gramos}:$
        - $\text{Proteina}: 0.01P + 0.2C + 0.15Cor + 0.04T \geq 9\ $
        - $\text{Grasa}: 0.08P + 0.1C + 0.11Cor + 0.01A + 0.01T \geq 7\ $
        - $\text{Fibra}: 0.001P + 0.005C + 0.005Cor + 0.1A + 0.15T \leq 2.5\ $
        - $\text{Sal}: 0.002P + 0.005C + 0.007Cor + 0.002A + 0.008T \geq 0.5\ $
   - $ \text{Peso}: P + C + Cor +  A +   T +  G = 100$

In [52]:
import numpy as np
import scipy.optimize as opt
c=np.array ([0.12, 0.009, 0.01, 0.003, 0.05, 0.002])
Aub=np.array([
    [-0.1,  -0.2,  -0.15,   0,  -0.4,   0],
    [-0.08, -0.1, -.01,  -0.01, -0.01,  0], 
    [0.001, 0.005, 0.005, 0.1,  0.15,   0], 
    [0.002, 0.002, 0.007, 0.002, 0.008, 0], 
    [  1,      1,     1,     1,    1,   1], 
])

bub=np.array ([-9, -7, 2.5, 5,100])

sol=opt.linprog(c, Aub, bub)
sol

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 0.63
              x: [ 0.000e+00  7.000e+01  0.000e+00  0.000e+00  0.000e+00
                   0.000e+00]
            nit: 1
          lower:  residual: [ 0.000e+00  7.000e+01  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
                 marginals: [ 1.128e-01  0.000e+00  9.100e-03  2.100e-03
                              4.910e-02  2.000e-03]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 5.000e+00  0.000e+00  2.150e+00  4.860e+00
                              3.000e+01]
                 marginals: [-0.000e+00 -9.000e-02 -0.000e

El costo de producción: $0.63

## Ejercicio 2

La Comisión Federal de Electricidad (CFE) dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas 1, 2 y 3 pueden satisfacer 75, 50 y 60 millones de kW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de 60, 45 y 60 millones de Kw al día respectivamente.
Los costos asociados al envío de suministro energético por cada millón de kW entre cada planta y cada ciudad son los registrados en la siguiente tabla:

![](Ejercicio2_A05.png)

1. Identificar criterio de optimizacion
   minimizar: $\$$ costo de producto como nuevo
   
2. Variables de control:
  - Planta 1 --> P1
  - Planta 2 --> P2
  - Planta 3 --> P3

    
  - Guadalajara --> G
      - GP1
      - GP2
      - GP3 
  - Leon --> L
      - LP1
      - LP2
      - LP3 
  - Morelia --> M
      - MP1
      - MP2
      - MP3 
    
3. Funcion de costo
   - $ GP1 (5) + GP2 (3) + GP3 (5) + LP1 (2) + LP2 (4) + LP3 (2) + MP1 (7) + MP2 (5) + MP3 (3) = Costo$

4. Informacion adicional
    - $\text{Capacidad}:$
        - $ GP1 + LP1 + MP1 \leq 75\ kw$
        - $ GP2 + LP2 + MP2 \leq 50\ kw$
        - $ GP3 + LP3 + MP3 \leq 60\ kw$



      
   - $\text{Necesidad}:$
        -  $ 60 = 5 GP1 + 3 GP2 + 5 GP3$
        - $ 45 = 2 LP1 + 4 LP2 + 2 LP3$
        - $ 60 = 7 MP1 + 5 MP2 + 3 MP3$

## A06

## Ejercicio 1

Una carpintería local fabrica sillas, mesas, libreros y bases de cama. Hay dos empleados en esta carpintería: un empleado experimentado y un aprendiz. El aprendiz tarda aproximadamente 50% más tiempo que el carpintero experimentado en construir cualquier cosa, además de que tiene un desperdicio de alrededor de 20% de material. Los materiales y tiempos necesarios para construir algo se desglozan en la siguiente tabla:

![](Ejercicio1_A06.png)

Las mesas se venden en $9000$, las sillas en $3000$, los libreros en $10000$, y las bases de cama en $9000$. Suponiendo una jornada de 40 horas a la semana y que tienen 100 unidades de madera, ¿qué les conviene construir durante una semana para maximizar su ganancia?

¿Cuántas horas trabaja cada quién?
¿Cuánto material se usa?
¿Cuál se el ingreso total si se vende todo lo fabricado?

1. Identificar criterio de optimizacion
   Maximizar: $\$$ las ganancias
   
2. Variables de control:
  - M_e --> Mesas experto
  - M_e --> Mesas aprendiz
  - S_e --> Sillas experto
  - S_a --> Sillas aprendiz
  - L_e --> Libreros experto
  - L_a --> Libreros aprendiz
  - B_e --> Bases experto
  - B_a --> Bases aprendiz

  - Mp --> 9000
  - Sp --> 3000
  - Lp --> 10000
  - Bp --> 9000


3. Funcion de costo
   - $ 9000M_e + 9000M_a + 3000M_e + 3000M_a + 10000L_e + 10000L_a + 9000B_e + 9000B_a = Costo$

4. Informacion adicional
    - $\text{Experimentado}:$ 
        - $ 3M_e + 1S_e + 4L_e + 3B_e \leq 40\ $
     
   - $\text{Aprendiz}:$
        - $ 4.5M_a + 1.5S_a + 6L_a + 4.5B_a \leq 40\ $
          
   - $\text{Material}:$
        - $ 6M_e + 7.2M_a + 2S_e + 2.4S_a + 5L_e + 6L_a + 5B_e + 6B_a \leq 100\ $

In [69]:
import numpy as np
import scipy.optimize as opt
c = np.array([-9000, -9000, -3000, -3000, -10000, -10000, -9000, -9000]) # Se pone negativa porque la función orginal es para maximizar

Aub = np.array ([
    [ 3,   0,   1,   0,    4,  0,  3,  0],
    [ 0,  4.5,  0,  1.5,   0,  6,  0,  4.5],
    [ 6,  7.2,  2,   2.4,    5,  6,  5,  6],
])

bub = np.array([
             40,
             40,
             100
])

opt.linprog(c, Aub, bub, integrality=1) 

# opt.linprog(c, Aub, bub, Acq, Bcg, integrity=1) hecho por el profe

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -176000.0
              x: [ 0.000e+00  0.000e+00  1.000e+00 -9.474e-15  9.000e+00
                   2.000e+00  1.000e+00  6.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  0.000e+00  1.000e+00 -9.474e-15
                              9.000e+00  2.000e+00  1.000e+00  6.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  1.000e+00  0.00

2. La carpintería recibió una orden por 3 combos de mesa + 6 sillas:
  - ¿Se puede cumplir la orden?
  - 
Si sí, ¿qué es lo que tienen que fabricar en el resto del tiempo y con el resto del material para maximizar su ganancia
  -  ¿Cuántas horas trabaja cada quién?
  - ¿Cuánto material se usa?
  - ¿Cuál es el nuevo ingreso total?

In [78]:
import numpy as np
import scipy.optimize as opt
c = np.array([-9000, -9000, -3000, -3000, -10000, -10000, -9000, -9000]) # Se pone negativa porque la función orginal es para maximizar

Aub=np.array([
    [4.5, 0, 1.5, 0, 6, 0, 4.5, 0], 
    [ 0,  3,  0,  1, 0, 4,  0,  3], 
    [7.2, 6, 2.4, 2, 6, 5,  6,  5],
    [-1, -1,  0,  0, 0, 0,  0,  0],
    [ 0,  0, -1, -1, 0, 0,  0,  0]
])
Bub=np.array([40, 40, 100, -3, -18])

opt.linprog(c, Aub, Bub, integrality=1)

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -161000.0
              x: [ 0.000e+00  3.000e+00  0.000e+00  1.800e+01  5.000e+00
                   3.000e+00  0.000e+00  0.000e+00]
            nit: -1
          lower:  residual: [ 0.000e+00  3.000e+00  0.000e+00  1.800e+01
                              5.000e+00  3.000e+00  0.000e+00  0.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 1.000e+01  1.000e+00  1.00

Pregunta 1
- Las ganancia total: 176000$ 
- Horas que trabajara el aprendiz serán 39 y el experto 40 
- Se usan las 100 unidades de madera. 

El novato hará: Sillas y libreros
El experto hará: Sillas, libreros y buros.

Pregunta 2:
- Las ganancia: 161000 
- Horas que trabajara el aprendiz serán 39 horas y el experto 30
- Se usan 99 unidades de madera.